version: "3.6"

services:
  so1:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    container_name: so1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_HEC_TOKEN=a9d40f5de-1d4d-4852-aad4-1b9e2c3f0166
      - SPLUNK_PASSWORD=password
    ports:
      - 8000:8000
      - 8088:8088